# Generated by Django 6.0.2 on 2026-02-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=120)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('abono', 'Abono'), ('pagado', 'Pagado'), ('cancelada', 'Cancelada')], default='reservada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
