# Generated by Django 6.0.2 on 2026-02-13 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='cita',
            name='duracion_minutos',
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(18, 0), '18:00')]),
        ),
    ]
