# Generated by Django 6.0.2 on 2026-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
