# Generated by Django 6.0.2 on 2026-02-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_cita_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
